# Generated by Django 5.2.4 on 2025-09-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(max_length=100)),
                ('province_city', models.CharField(max_length=100)),
                ('ward_commune', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('coordinate', models.TextField()),
            ],
            options={
                'db_table': 'post_offices',
            },
        ),
    ]
