# Generated by Django 5.2.4 on 2025-10-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_offices", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postoffice",
            name="coordinate",
        ),
        migrations.AddField(
            model_name="postoffice",
            name="latitude",
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="postoffice",
            name="longitude",
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
