# Generated by Django 5.2.4 on 2025-10-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "post_offices",
            "0002_remove_postoffice_coordinate_postoffice_latitude_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="postoffice",
            name="district",
            field=models.CharField(default="Huong Thuy", max_length=100),
            preserve_default=False,
        ),
    ]
