# Generated by Django 5.2.4 on 2025-10-26 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post_offices", "0003_postoffice_district"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postoffice",
            name="district",
        ),
        migrations.RemoveField(
            model_name="postoffice",
            name="province_city",
        ),
        migrations.RemoveField(
            model_name="postoffice",
            name="ward_commune",
        ),
    ]
