# Generated by Django 5.2.4 on 2025-10-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_offices", "0004_remove_postoffice_district_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postoffice",
            name="district",
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="postoffice",
            name="province_city",
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="postoffice",
            name="ward_commune",
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
    ]
