# Generated by Django 5.2.4 on 2025-11-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_offices", "0005_postoffice_district_postoffice_province_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postoffice",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="postoffice",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
