# Generated by Django 5.2.4 on 2025-12-02 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post_offices", "0006_alter_postoffice_latitude_alter_postoffice_longitude"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postoffice",
            options={
                "permissions": [
                    ("add_shipper", "Can add shipper to post office"),
                    ("add_staff", "Can add staff to post office"),
                ]
            },
        ),
    ]
