# Generated by Django 5.2.4 on 2025-12-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post_offices", "0007_alter_postoffice_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postoffice",
            options={
                "permissions": [
                    ("add_shipper", "Can add shipper to post office"),
                    ("add_staff", "Can add staff to post office"),
                    ("edit_user", "Can edit user of a post office"),
                ]
            },
        ),
    ]
