# Generated by Django 5.2.4 on 2025-12-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_offices", "0010_alter_postoffice_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postoffice",
            name="district",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="postoffice",
            name="province_city",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="postoffice",
            name="ward_commune",
            field=models.CharField(max_length=20),
        ),
    ]
