export enum ShippingStatus {
  PICKUP_REQUESTED = 'PICKUP_REQUESTED',
  SHIPPING = 'SHIPPING',
  RETURNING = 'RETURNING',
  FINISHED = 'FINISHED',
  FAILED = 'FAILED',
  PICKUP_FAILED = 'PICKUP_FAILED',
  DELIVERY_FAILED = 'DELIVERY_FAILED',
}
