export enum ShippingStatus {
  PICKUP_REQUESTED = 'PICKUP_REQUESTED',
  IN_TRANSIT = 'IN_TRANSIT',
  CLASSIFIED = 'CLASSIFIED',
  IN_WAREHOUSE = 'IN_WAREHOUSE',
  SHIPPING = 'SHIPPING',
  PICKUP_FAILED = 'PICKUP_FAILED',
  DELIVERY_FAILED = 'DELIVERY_FAILED',
  RETURNING = 'RETURNING',
  FINISHED = 'FINISHED',
}
