# Generated by Django 5.2.4 on 2025-10-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "SUPER_ADMIN"),
                    ("admin", "ADMIN"),
                    ("post_office_manager", "POST_OFFICE_MANAGER"),
                    ("post_office_staff", "POST_OFFICE_STAFF"),
                    ("shop", "SHOP"),
                    ("shipper", "SHIPPER"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
