# Generated by Django 5.2.4 on 2025-10-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0003_alter_adminprofile_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="exclude_permissions",
            field=models.ManyToManyField(
                db_table="user_exclude_permissions",
                related_name="exclude_users",
                to="auth.permission",
            ),
        ),
    ]
