# Generated by Django 5.2.4 on 2025-10-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_exclude_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipperprofile",
            name="address",
            field=models.TextField(default="83 Thanh Vinh 8, Hoa Khanh Bac, Da Nang"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipperprofile",
            name="avatar",
            field=models.ImageField(null=True, upload_to="public/shipper_avatar/"),
        ),
        migrations.AddField(
            model_name="shipperprofile",
            name="card_id",
            field=models.CharField(default="04649284725", max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipperprofile",
            name="motor_model",
            field=models.CharField(default="Air blade", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipperprofile",
            name="motor_model_release_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipperprofile",
            name="phone_number",
            field=models.CharField(default="0492847265", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shopprofile",
            name="address",
            field=models.TextField(default="609 Nguyen Tat Thanh, Hue"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shopprofile",
            name="phone_number",
            field=models.CharField(default="0492857264", max_length=10),
            preserve_default=False,
        ),
    ]
