# Generated by Django 5.2.4 on 2025-10-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_shipperprofile_address_shipperprofile_avatar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipperprofile",
            name="motor_model_release_year",
        ),
        migrations.AddField(
            model_name="shipperprofile",
            name="license_plate_number",
            field=models.CharField(default="75A-01245", max_length=100),
            preserve_default=False,
        ),
    ]
