# Generated by Django 5.2.4 on 2025-11-07 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_offices", "0006_alter_postoffice_latitude_alter_postoffice_longitude"),
        ("users", "0007_passwordresetotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopprofile",
            name="latitude",
            field=models.DecimalField(
                decimal_places=6, default=16.424388, max_digits=9
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shopprofile",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6, default=107.656812, max_digits=9
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shopprofile",
            name="post_office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="post_offices.postoffice",
            ),
        ),
    ]
