version: '3.8'

services:
  admin:
    build:
      context: .
      dockerfile: dockerfile
    container_name: express-mail-admin
    ports:
      - "4173:4173"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - express-mail-network

networks:
  express-mail-network:
    driver: bridge