# Generated by Django 5.2.4 on 2025-11-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Routing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [("call_vrp", "Can call VRP API")],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
