# Generated by Django 5.2.4 on 2025-12-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_auth", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesstokenwhitelist",
            name="token",
            field=models.TextField(unique=True),
        ),
    ]
