# Generated by Django 5.2.4 on 2025-10-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShippingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("base_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rate_per_km", models.DecimalField(decimal_places=2, max_digits=10)),
                ("volumetric_divisor", models.IntegerField(default=5000)),
                ("rate_per_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                ("effective_from", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "shipping_rate",
            },
        ),
    ]
