# Generated by Django 5.2.4 on 2025-10-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingrate",
            name="effective_from",
        ),
        migrations.AddField(
            model_name="shippingrate",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
