# Generated by Django 5.2.4 on 2025-10-29 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0002_remove_shippingrate_effective_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingrate",
            name="base_fee",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="shippingrate",
            name="rate_per_kg",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="shippingrate",
            name="rate_per_km",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="shippingrate",
            name="volumetric_divisor",
            field=models.IntegerField(
                default=5000, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
