# Generated by Django 5.2.4 on 2025-10-29 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0003_alter_shippingrate_base_fee_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shippingrate",
            options={
                "permissions": [
                    ("change_shippingrate_status", "Can change shipping rate status")
                ]
            },
        ),
    ]
