name: Deploy Post Office Frontend

on:
  push:
    paths:
      - 'system-post-office/**'
    branches:
      - develop

concurrency:
  group: post-office-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: SSH and deploy Post Office Frontend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.FE_EC2_HOST }}
          username: ${{ secrets.FE_EC2_USER }}
          key: ${{ secrets.FE_EC2_KEY }}
          script: |
            cd /home/ec2-user/Express-Mail/system-post-office
            git pull origin develop
            docker compose up -d --build

