name: Deploy Django API

on:
  push:
    paths:
      - 'express-mail-django-api/**'
    branches:
      - develop

concurrency:
  group: django-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: SSH and deploy Django API
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_DJANGO_HOST }}
          username: ${{ secrets.EC2_DJANGO_USER }}
          key: ${{ secrets.EC2_DJANGO_API }}
          script: |
            cd /home/ec2-user/Express-Mail/express-mail-django-api
            git pull origin develop
            docker-compose -f docker-compose.prod.yml up --build -d
            docker-compose -f docker-compose.prod.yml exec api python manage.py migrate
